import { ExternalLink, ShieldCheck, Database, Building2 } from 'lucide-react';

export const OFFICIAL_MPLADS_PORTAL_URL = "https://mplads.gov.in";

export default function ProvenanceFooter() {
  return (
    <footer className="provenance-footer-card" id="section-provenance">
      <div className="provenance-grid">
        <div className="provenance-left">
          <div className="provenance-brand-row">
            <Building2 size={16} />
            <span className="provenance-title">Source & Data Provenance</span>
          </div>
          <p className="provenance-text">
            FundGuard AI analyzes publicly available MPLADS records. Analytical results are generated by FundGuard AI and should be verified against the original government records. FundGuard AI does not claim continuous surveillance and identifies candidates strictly for administrative audit review.
          </p>
          <div className="provenance-tags-row">
            <span className="prov-tag">Source: Ministry of Statistics & Programme Implementation (MoSPI)</span>
            <span className="prov-tag">Coverage: 36 States / UTs</span>
            <span className="prov-tag">Record Count: 297,398</span>
          </div>
        </div>

        <div className="provenance-right">
          <a 
            href={OFFICIAL_MPLADS_PORTAL_URL} 
            target="_blank" 
            rel="noopener noreferrer" 
            className="btn-provenance"
          >
            <span>VIEW ORIGINAL MPLADS DATA</span>
            <ExternalLink size={13} />
          </a>
          <span className="provenance-subnote">Opens official Government of India MPLADS portal</span>
        </div>
      </div>
    </footer>
  );
}
